name: Run Main Script on Commit

on:
  push:
    branches:
      - main  # or whatever your main branch is called

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # specify your Python version here

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # If you have any dependencies listed in requirements.txt

    - name: Run main.py
      run: python main.py
