name: Run Main Script Daily at 00:00 UTC

on:
  schedule:
    - cron: '0 0 * * *'  # Run every 6 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run main.py
      run: python main.py
